# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class EndpointMethod(str, enum.Enum):
    PUT = "PUT"
    POST = "POST"
    GET = "GET"
    PATCH = "PATCH"
    DELETE = "DELETE"

    def visit(
        self,
        put: typing.Callable[[], T_Result],
        post: typing.Callable[[], T_Result],
        get: typing.Callable[[], T_Result],
        patch: typing.Callable[[], T_Result],
        delete: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EndpointMethod.PUT:
            return put()
        if self is EndpointMethod.POST:
            return post()
        if self is EndpointMethod.GET:
            return get()
        if self is EndpointMethod.PATCH:
            return patch()
        if self is EndpointMethod.DELETE:
            return delete()
