# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Availability(str, enum.Enum):
    GENERALLY_AVAILABLE = "GenerallyAvailable"
    DEPRECATED = "Deprecated"
    BETA = "Beta"

    def visit(
        self,
        generally_available: typing.Callable[[], T_Result],
        deprecated: typing.Callable[[], T_Result],
        beta: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is Availability.GENERALLY_AVAILABLE:
            return generally_available()
        if self is Availability.DEPRECATED:
            return deprecated()
        if self is Availability.BETA:
            return beta()
