# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from ...type.types.object_type import ObjectType


class HttpRequestBodyShape_Object(ObjectType):
    type: typing_extensions.Literal["object"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class HttpRequestBodyShape_Reference(pydantic.BaseModel):
    type: typing_extensions.Literal["reference"]
    value: TypeReference

    class Config:
        frozen = True
        smart_union = True


class HttpRequestBodyShape_FileUpload(pydantic.BaseModel):
    type: typing_extensions.Literal["fileUpload"]

    class Config:
        frozen = True
        smart_union = True


HttpRequestBodyShape = typing.Union[
    HttpRequestBodyShape_Object, HttpRequestBodyShape_Reference, HttpRequestBodyShape_FileUpload
]
from ...type.types.type_reference import TypeReference  # noqa: E402
