# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .color_themed_config import ColorThemedConfig
from .color_unthemed_config import ColorUnthemedConfig


class ColorConfig_Unthemed(ColorUnthemedConfig):
    type: typing_extensions.Literal["unthemed"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ColorConfig_Themed(ColorThemedConfig):
    type: typing_extensions.Literal["themed"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ColorConfig = typing.Union[ColorConfig_Unthemed, ColorConfig_Themed]
