# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .navbar_primary_link import NavbarPrimaryLink
from .navbar_secondary_link import NavbarSecondaryLink


class NavbarLink_Primary(NavbarPrimaryLink):
    type: typing_extensions.Literal["primary"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class NavbarLink_Secondary(NavbarSecondaryLink):
    type: typing_extensions.Literal["secondary"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


NavbarLink = typing.Union[NavbarLink_Primary, NavbarLink_Secondary]
