# This file was auto-generated by Fern from our API Definition.

import typing

from .unversioned_navigation_config import UnversionedNavigationConfig
from .versioned_navigation_config import VersionedNavigationConfig

NavigationConfig = typing.Union[UnversionedNavigationConfig, VersionedNavigationConfig]
