# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .basic_auth_payload import BasicAuthPayload
from .bearer_token_auth_payload import BearerTokenAuthPayload


class AuthPayload_Bearer(BearerTokenAuthPayload):
    type: typing.Literal["bearer"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class AuthPayload_Basic(BasicAuthPayload):
    type: typing.Literal["basic"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


AuthPayload = typing.Union[AuthPayload_Bearer, AuthPayload_Basic]
