# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .go_sdk import GoSdk
from .java_sdk import JavaSdk
from .python_sdk import PythonSdk
from .type_script_sdk import TypeScriptSdk


class Sdk_Typescript(TypeScriptSdk):
    type: typing.Literal["typescript"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Sdk_Python(PythonSdk):
    type: typing.Literal["python"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Sdk_Go(GoSdk):
    type: typing.Literal["go"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Sdk_Java(JavaSdk):
    type: typing.Literal["java"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


Sdk = typing.Union[Sdk_Typescript, Sdk_Python, Sdk_Go, Sdk_Java]
