# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .go_sdk_request import GoSdkRequest
from .java_sdk_request import JavaSdkRequest
from .python_sdk_request import PythonSdkRequest
from .ruby_sdk_request import RubySdkRequest
from .type_script_sdk_request import TypeScriptSdkRequest


class SdkRequest_Typescript(TypeScriptSdkRequest):
    type: typing.Literal["typescript"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class SdkRequest_Python(PythonSdkRequest):
    type: typing.Literal["python"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class SdkRequest_Go(GoSdkRequest):
    type: typing.Literal["go"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class SdkRequest_Ruby(RubySdkRequest):
    type: typing.Literal["ruby"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class SdkRequest_Java(JavaSdkRequest):
    type: typing.Literal["java"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


SdkRequest = typing.Union[SdkRequest_Typescript, SdkRequest_Python, SdkRequest_Go, SdkRequest_Ruby, SdkRequest_Java]
