# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class SnippetLoadLevel(str, enum.Enum):
    FULL = "full"
    """
    The full snippet including client instantiation and method call.
    """

    ENDPOINT = "endpoint"
    """
    Only returns the part of the snippet for the endpoint call. In
    other words, the client instantiation is not included.
    """

    def visit(self, full: typing.Callable[[], T_Result], endpoint: typing.Callable[[], T_Result]) -> T_Result:
        if self is SnippetLoadLevel.FULL:
            return full()
        if self is SnippetLoadLevel.ENDPOINT:
            return endpoint()
