# This file was auto-generated by Fern from our API Definition.

import typing

from .endpoint_method import EndpointMethod
from .snippet import Snippet

SnippetsByEndpointMethod = typing.Dict[EndpointMethod, typing.List[Snippet]]
