# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .go_snippet import GoSnippet
from .java_snippet import JavaSnippet
from .python_snippet import PythonSnippet
from .type_script_snippet import TypeScriptSnippet


class Snippet_Typescript(TypeScriptSnippet):
    type: typing.Literal["typescript"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Snippet_Python(PythonSnippet):
    type: typing.Literal["python"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Snippet_Java(JavaSnippet):
    type: typing.Literal["java"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Snippet_Go(GoSnippet):
    type: typing.Literal["go"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


Snippet = typing.Union[Snippet_Typescript, Snippet_Python, Snippet_Java, Snippet_Go]
