# This file was auto-generated by Fern from our API Definition.

import os

import pytest
from fern.client import AsyncFern, Fern


@pytest.fixture
def client() -> Fern:
    return Fern(token=os.getenv("ENV_TOKEN", "token"), base_url=os.getenv("TESTS_BASE_URL", "base_url"))


@pytest.fixture
def async_client() -> AsyncFern:
    return AsyncFern(token=os.getenv("ENV_TOKEN", "token"), base_url=os.getenv("TESTS_BASE_URL", "base_url"))
