# This file was auto-generated by Fern from our API Definition.

from fern.client import AsyncFern, Fern

from .utilities import validate_response


async def test_generate(client: Fern, async_client: AsyncFern) -> None:
    expected_response = {"token": "token", "id": "id"}
    response = client.tokens.generate(org_id="orgId", scope="scope")
    validate_response(response, expected_response)

    async_response = await async_client.tokens.generate(org_id="orgId", scope="scope")
    validate_response(async_response, expected_response)


async def test_revoke(client: Fern, async_client: AsyncFern) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert client.tokens.revoke(org_id="orgId", token_id="tokenId") is None  # type: ignore[func-returns-value]

    assert await async_client.tokens.revoke(org_id="orgId", token_id="tokenId") is None  # type: ignore[func-returns-value]
