# This file was auto-generated by Fern from our API Definition.

from fern.client import AsyncFern, Fern

from fern import ApiDefinition_Openapi, SdkLanguage, SdkPublishingConfiguration

from .utilities import validate_response


async def test_generate(client: Fern, async_client: AsyncFern) -> None:
    expected_response = {"jobId": "jobId"}
    response = client.sdk.generate(
        api=ApiDefinition_Openapi(type="openapi", value={"key": "value"}),
        language=SdkLanguage.TYPESCRIPT,
        publishing=SdkPublishingConfiguration(),
    )
    validate_response(response, expected_response)

    async_response = await async_client.sdk.generate(
        api=ApiDefinition_Openapi(type="openapi", value={"key": "value"}),
        language=SdkLanguage.TYPESCRIPT,
        publishing=SdkPublishingConfiguration(),
    )
    validate_response(async_response, expected_response)


async def test_get_status(client: Fern, async_client: AsyncFern) -> None:
    expected_response = {"type": "running", "estimatedTimeRemainingSeconds": 1}
    response = client.sdk.get_status(job_id="jobId")
    validate_response(response, expected_response)

    async_response = await async_client.sdk.get_status(job_id="jobId")
    validate_response(async_response, expected_response)
