# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class WebhookHttpMethod(str, enum.Enum):
    GET = "GET"
    POST = "POST"

    def visit(self, get: typing.Callable[[], T_Result], post: typing.Callable[[], T_Result]) -> T_Result:
        if self is WebhookHttpMethod.GET:
            return get()
        if self is WebhookHttpMethod.POST:
            return post()
