# This file was auto-generated by Fern from our API Definition.

from ..........core.api_error import ApiError
from ..types.endpoint_example_generation_error_body import EndpointExampleGenerationErrorBody


class EndpointExampleGenerationError(ApiError):
    def __init__(self, body: EndpointExampleGenerationErrorBody):
        super().__init__(status_code=500, body=body)
