# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .algolia_endpoint_record import AlgoliaEndpointRecord
from .algolia_endpoint_record_v_2 import AlgoliaEndpointRecordV2
from .algolia_page_record import AlgoliaPageRecord
from .algolia_page_record_v_2 import AlgoliaPageRecordV2


class AlgoliaRecord_Endpoint(AlgoliaEndpointRecord):
    type: typing_extensions.Literal["endpoint"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class AlgoliaRecord_Page(AlgoliaPageRecord):
    type: typing_extensions.Literal["page"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class AlgoliaRecord_EndpointV2(AlgoliaEndpointRecordV2):
    type: typing_extensions.Literal["endpoint-v2"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class AlgoliaRecord_PageV2(AlgoliaPageRecordV2):
    type: typing_extensions.Literal["page-v2"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


AlgoliaRecord = typing.Union[AlgoliaRecord_Endpoint, AlgoliaRecord_Page, AlgoliaRecord_EndpointV2, AlgoliaRecord_PageV2]
