# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from .rgb_color import RgbColor


class Background_Solid(RgbColor):
    type: typing_extensions.Literal["solid"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class Background_Gradient(pydantic.BaseModel):
    type: typing_extensions.Literal["gradient"]

    class Config:
        frozen = True
        smart_union = True


Background = typing.Union[Background_Solid, Background_Gradient]
