# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .dark_and_light_mode_config import DarkAndLightModeConfig
from .dark_mode_config import DarkModeConfig
from .light_mode_config import LightModeConfig


class ColorsConfigV3_Dark(DarkModeConfig):
    type: typing_extensions.Literal["dark"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ColorsConfigV3_Light(LightModeConfig):
    type: typing_extensions.Literal["light"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ColorsConfigV3_DarkAndLight(DarkAndLightModeConfig):
    type: typing_extensions.Literal["darkAndLight"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ColorsConfigV3 = typing.Union[ColorsConfigV3_Dark, ColorsConfigV3_Light, ColorsConfigV3_DarkAndLight]
