# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .maven_package import MavenPackage
from .npm_package import NpmPackage
from .pypi_package import PypiPackage


class PublishedSdk_Npm(NpmPackage):
    type: typing_extensions.Literal["npm"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PublishedSdk_Maven(MavenPackage):
    type: typing_extensions.Literal["maven"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PublishedSdk_Pypi(PypiPackage):
    type: typing_extensions.Literal["pypi"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


PublishedSdk = typing.Union[PublishedSdk_Npm, PublishedSdk_Maven, PublishedSdk_Pypi]
