# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .unversioned_single_algolia_index_info import UnversionedSingleAlgoliaIndexInfo
from .versioned_single_algolia_index_info import VersionedSingleAlgoliaIndexInfo


class SingleAlgoliaIndexInfo_Unversioned(UnversionedSingleAlgoliaIndexInfo):
    type: typing_extensions.Literal["unversioned"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class SingleAlgoliaIndexInfo_Versioned(VersionedSingleAlgoliaIndexInfo):
    type: typing_extensions.Literal["versioned"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


SingleAlgoliaIndexInfo = typing.Union[SingleAlgoliaIndexInfo_Unversioned, SingleAlgoliaIndexInfo_Versioned]
