# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class VersionAvailability(str, enum.Enum):
    STABLE = "Stable"
    GENERALLY_AVAILABLE = "GenerallyAvailable"
    DEPRECATED = "Deprecated"
    BETA = "Beta"

    def visit(
        self,
        stable: typing.Callable[[], T_Result],
        generally_available: typing.Callable[[], T_Result],
        deprecated: typing.Callable[[], T_Result],
        beta: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is VersionAvailability.STABLE:
            return stable()
        if self is VersionAvailability.GENERALLY_AVAILABLE:
            return generally_available()
        if self is VersionAvailability.DEPRECATED:
            return deprecated()
        if self is VersionAvailability.BETA:
            return beta()
