# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class ApiDefinition_Openapi(pydantic.BaseModel):
    type: typing.Literal["openapi"]
    value: typing.Any

    class Config:
        frozen = True
        smart_union = True


class ApiDefinition_Postman(pydantic.BaseModel):
    type: typing.Literal["postman"]
    value: typing.Any

    class Config:
        frozen = True
        smart_union = True


class ApiDefinition_Fern(pydantic.BaseModel):
    type: typing.Literal["fern"]
    value: typing.Any

    class Config:
        frozen = True
        smart_union = True


ApiDefinition = typing.Union[ApiDefinition_Openapi, ApiDefinition_Postman, ApiDefinition_Fern]
