# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .maven_publshing_configuration import MavenPublshingConfiguration
from .npm_publishing_configuration import NpmPublishingConfiguration
from .nuget_publishing_configuration import NugetPublishingConfiguration
from .packagist_publishing_configuration import PackagistPublishingConfiguration
from .pypi_publishing_configuration import PypiPublishingConfiguration
from .ruby_gems_publishing_configuration import RubyGemsPublishingConfiguration


class Registry_Npm(NpmPublishingConfiguration):
    type: typing.Literal["npm"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Registry_Pypi(PypiPublishingConfiguration):
    type: typing.Literal["pypi"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Registry_Maven(MavenPublshingConfiguration):
    type: typing.Literal["maven"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Registry_Nuget(NugetPublishingConfiguration):
    type: typing.Literal["nuget"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Registry_RubyGems(RubyGemsPublishingConfiguration):
    type: typing.Literal["rubyGems"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Registry_Packagist(PackagistPublishingConfiguration):
    type: typing.Literal["packagist"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


Registry = typing.Union[
    Registry_Npm, Registry_Pypi, Registry_Maven, Registry_Nuget, Registry_RubyGems, Registry_Packagist
]
