# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .git_hub_repository import GitHubRepository
from .git_lab_repository import GitLabRepository


class Repository_Github(GitHubRepository):
    type: typing.Literal["github"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class Repository_Gitlab(GitLabRepository):
    type: typing.Literal["gitlab"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


Repository = typing.Union[Repository_Github, Repository_Gitlab]
