# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .completed_sdk_generation_status import CompletedSdkGenerationStatus
from .failed_sdk_generation_status import FailedSdkGenerationStatus
from .running_sdk_generation_status import RunningSdkGenerationStatus


class SdkGenerationStatus_Running(RunningSdkGenerationStatus):
    type: typing.Literal["running"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class SdkGenerationStatus_Completed(CompletedSdkGenerationStatus):
    type: typing.Literal["completed"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


class SdkGenerationStatus_Failed(FailedSdkGenerationStatus):
    type: typing.Literal["failed"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True


SdkGenerationStatus = typing.Union[
    SdkGenerationStatus_Running, SdkGenerationStatus_Completed, SdkGenerationStatus_Failed
]
