# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .basic_auth import BasicAuth
from .bearer_auth import BearerAuth
from .header_auth import HeaderAuth


class ApiAuth_BearerAuth(BearerAuth):
    type: typing_extensions.Literal["bearerAuth"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ApiAuth_BasicAuth(BasicAuth):
    type: typing_extensions.Literal["basicAuth"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ApiAuth_Header(HeaderAuth):
    type: typing_extensions.Literal["header"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ApiAuth = typing.Union[ApiAuth_BearerAuth, ApiAuth_BasicAuth, ApiAuth_Header]
