# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions


class LiteralType_StringLiteral(pydantic.BaseModel):
    type: typing_extensions.Literal["stringLiteral"]
    value: str

    class Config:
        frozen = True
        smart_union = True


LiteralType = typing.Union[LiteralType_StringLiteral]
