# This file was auto-generated by Fern from our API Definition.

from .......core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.read.client import AsyncReadClient, ReadClient
from .resources.write.client import AsyncWriteClient, WriteClient


class V2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.read = ReadClient(client_wrapper=self._client_wrapper)
        self.write = WriteClient(client_wrapper=self._client_wrapper)


class AsyncV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.read = AsyncReadClient(client_wrapper=self._client_wrapper)
        self.write = AsyncWriteClient(client_wrapper=self._client_wrapper)
