# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ............core.datetime_utils import serialize_datetime
from ...commons.types.with_description import WithDescription
from .availability import Availability
from .endpoint_id import EndpointId
from .endpoint_path import EndpointPath
from .environment import Environment
from .environment_id import EnvironmentId
from .error_declaration import ErrorDeclaration
from .error_declaration_v_2 import ErrorDeclarationV2
from .example_endpoint_call import ExampleEndpointCall
from .header import Header
from .http_method import HttpMethod
from .http_request import HttpRequest
from .http_response import HttpResponse
from .query_parameter import QueryParameter


class EndpointDefinition(WithDescription):
    auth: typing.Optional[bool]
    availability: typing.Optional[Availability]
    default_environment: typing.Optional[EnvironmentId] = pydantic.Field(alias="defaultEnvironment")
    environments: typing.Optional[typing.List[Environment]]
    method: HttpMethod
    id: EndpointId
    name: typing.Optional[str]
    path: EndpointPath
    query_parameters: typing.List[QueryParameter] = pydantic.Field(alias="queryParameters")
    headers: typing.List[Header]
    request: typing.Optional[HttpRequest]
    response: typing.Optional[HttpResponse]
    errors: typing.Optional[typing.List[ErrorDeclaration]]
    errors_v_2: typing.Optional[typing.List[ErrorDeclarationV2]] = pydantic.Field(alias="errorsV2")
    examples: typing.List[ExampleEndpointCall]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
