# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from .path_parameter_key import PathParameterKey


class EndpointPathPart_Literal(pydantic.BaseModel):
    type: typing_extensions.Literal["literal"]
    value: str

    class Config:
        frozen = True
        smart_union = True


class EndpointPathPart_PathParameter(pydantic.BaseModel):
    type: typing_extensions.Literal["pathParameter"]
    value: PathParameterKey

    class Config:
        frozen = True
        smart_union = True


EndpointPathPart = typing.Union[EndpointPathPart_Literal, EndpointPathPart_PathParameter]
