# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..........core.datetime_utils import serialize_datetime
from .......commons.types.api_definition_id import ApiDefinitionId
from ...read.types.api_artifacts import ApiArtifacts


class ApiSection(pydantic.BaseModel):
    title: str
    api: ApiDefinitionId
    url_slug: str = pydantic.Field(alias="urlSlug")
    skip_url_slug: bool = pydantic.Field(alias="skipUrlSlug")
    artifacts: typing.Optional[ApiArtifacts]
    show_errors: typing.Optional[bool] = pydantic.Field(alias="showErrors")

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
