# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from ...read.types.page_metadata import PageMetadata
from .api_section import ApiSection


class NavigationItem_Page(PageMetadata):
    type: typing_extensions.Literal["page"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class NavigationItem_Api(ApiSection):
    type: typing_extensions.Literal["api"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class NavigationItem_Section(DocsSection):
    type: typing_extensions.Literal["section"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


NavigationItem = typing.Union[NavigationItem_Page, NavigationItem_Api, NavigationItem_Section]
from .docs_section import DocsSection  # noqa: E402

NavigationItem_Section.update_forward_refs(DocsSection=DocsSection, NavigationItem=NavigationItem)
