# This file was auto-generated by Fern from our API Definition.

import typing

from .unversioned_tabbed_navigation_config import UnversionedTabbedNavigationConfig
from .unversioned_untabbed_navigation_config import UnversionedUntabbedNavigationConfig

UnversionedNavigationConfig = typing.Union[UnversionedTabbedNavigationConfig, UnversionedUntabbedNavigationConfig]
